### ISSUE TITLE
blueprint2swagger

### ISSUE THREAD

**Issue by SamuelMarks** [apiaryio/swagger2blueprint#10]
I like the look of this project! - Are there plans to go in the other direction also?

**Comment by zdne** [comment]
@SamuelMarks indirectly yes. This is build upon the [Fury project](https://github.com/apiaryio/fury.js) and the concept of canonical [API Refract](https://github.com/refractproject/refract-spec/blob/master/namespaces/api-namespace.md). So if somebody extends Fury.js Swagger adapter with serialization it would be possible.

**Comment by SamuelMarks** [comment]
Excellent, looking forward to this being done.

**Comment by SamuelMarks** [comment]
Haven't tried this yet, but looks like it might do it (+ it's being maintained): https://github.com/kminami/apib2swagger
