### ISSUE TITLE
Problems installing on recent nodes

### ISSUE THREAD

**Issue by netmilk** [apiaryio/swagger2blueprint#19]
On node v4.2.2. Reported by an Apiary user, no additional information provided.
 
![image](https://cloud.githubusercontent.com/assets/79609/12451055/72bb8708-bf87-11e5-9300-028a32dc5a0f.png)

**Comment by kylef** [comment]
This is expected. The README mentions the supported node versions:

> Note, at the moment the tool supports only Node.js v0.10. It does not work with Node.js (or io.js) higher than v0.10.

Shouldn't be too hard to update this to use the newer version of fury/swagger adapter which works on newer nodes though.

**Comment by zdne** [comment]
Seems like a duplicate to #9

**Comment by kylef** [comment]
Node 3, 4 and 5 support has been added in swagger2blueprint 1.0.2.
