### ISSUE TITLE
`HOST` field missing

### ISSUE THREAD

**Issue by theandym** [apiaryio/swagger2blueprint#24]
When converting, the resulting API Blueprint file is missing the `HOST` key/value in the metadata section.

Swagger input:

```
# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Uber API
  description: Move your app forward with the Uber API
  version: "1.0.0"
# the domain of the service
host: api.uber.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json

...
```

API Blueprint output:

```
FORMAT: 1A

# Uber API

Move your app forward with the Uber API

...
```

**Comment by kylef** [comment]
This tool has been deprecated in favour of Fury CLI. (https://github.com/apiaryio/swagger2blueprint/pull/27)

You can find instructions for using Fury CLI to convert Swagger documents at https://github.com/apiaryio/fury-cli#converting-swagger-to-api-blueprint.

This problem has been resolved in Fury CLI.
